services:
  app:
    build: ./app
    ports:
      - "3000:3000"
    environment:
      # Sửa hostname ở đây
      - DATABASE_URL=postgresql://postgres:password@cloudpilot:5432/postgres
    depends_on:
      # Sửa tên service phụ thuộc ở đây
      - cloudpilot

  # Sửa tên service ở đây
  cloudpilot:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: