apiVersion: v1
kind: Secret
metadata:
  name: openldap-secret
  namespace: autoops
type: Opaque
data:
  # Base64 encode cho mật khẩu admin của bạn, ví dụ: echo -n 'adminpassword' | base64
  LDAP_ADMIN_PASSWORD: YWRtaW5wYXNzd29yZA==